/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#f0a878",
        "surface-bright": "#faf5ee",
        outline: "#9a9088",
        "on-primary-fixed": "#401a08",
        secondary: "#78706a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#2e1515",
        "surface-dim": "#dcd6cc",
        "secondary-fixed-dim": "#cec6be",
        "on-surface-variant": "#605850",
        "tertiary-container": "#d47070",
        "outline-variant": "#d8d0c8",
        "surface-container-high": "#ece6dc",
        "on-error": "#ffffff",
        "inverse-on-surface": "#faf5ee",
        "on-surface": "#3a302a",
        "on-secondary": "#ffffff",
        "inverse-primary": "#f0a878",
        "tertiary-fixed": "#fce0e0",
        "on-tertiary-container": "#3a2020",
        "on-primary-container": "#fbe8d8",
        "primary-container": "#e08850",
        "secondary-container": "#eae2da",
        "on-primary-fixed-variant": "#8a4518",
        "on-background": "#3a302a",
        surface: "#faf5ee",
        "on-secondary-fixed": "#2a2420",
        "surface-tint": "#c2652a",
        "tertiary-fixed-dim": "#e8a0a0",
        "inverse-surface": "#3a302a",
        "on-tertiary-fixed-variant": "#6e3030",
        tertiary: "#8c3c3c",
        "on-secondary-container": "#605850",
        error: "#c0392b",
        "surface-container-low": "#f6f0e8",
        "primary-fixed": "#fbe8d8",
        "surface-container-highest": "#e6e0d6",
        "error-container": "#fce4e0",
        "on-error-container": "#7a1a10",
        "surface-container": "#f2ece4",
        "on-primary": "#ffffff",
        background: "#faf5ee",
        primary: "#c2652a",
        "surface-variant": "#ece6dc",
        "on-secondary-fixed-variant": "#504840",
        "secondary-fixed": "#eae2da",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "320px",
        "margin-page": "40px",
        gutter: "24px",
        "container-max": "1100px",
        "stack-gap": "16px",
        "section-padding": "64px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-lg": ["Montserrat"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Montserrat"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Montserrat"],
        "headline-md": ["Montserrat"],
        "headline-sm": ["Montserrat"],
        headline: ["Eb Garamond"],
        display: ["Eb Garamond"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      boxShadow: {
        "level-2": "0px 4px 20px rgba(0, 0, 0, 0.05)",
      },
    },
  },
};
